### ISSUE TITLE
[Bug]: Unable to use multiple RichEditors on Subsequent Wizard Steps

### ISSUE THREAD

**Issue by elegasoft** [schmeits/filament-character-counter#11] opened 2024-08-28 18:31 UTC
### What happened?

Cannot use `RichEditor` on subsequent `Wizard\Step`, it will work just fine on the first Step but a `RichEditor` on a subsequent step will not allow you to obtain a cursor.

### How to reproduce the bug

```php
<?php

use Filament\Forms\Components\{Wizard, Wizard\Step};
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Schmeits\FilamentCharacterCounter\Forms\Components\{RichEditor};

class TestFilamentResource extends Resource
{

    public static function form(Form $form): Form
    {
        return $form
            ->columns(1)
            ->schema([
                Wizard::make()->schema([
                    Step::make('start')->schema([
                        TextInput::make('regular_text_input')
                                 ->label('Regular Text Input'),
                    ]),
                    Step::make('Working Editor Step')->schema([
                        RichEditor::make('working_rich_editor')
                                  ->label('Working Rich Editor'),
                    ]),
                    Step::make('Broken Editor Step')->schema([
                        RichEditor::make('broken_rich_editor')
                                  ->label('Broken Rich Editor'),
                    ]),
                ]),
            ]);
    }
}



```

### Package Version

1.3.1

### PHP Version

8.3.10

### Laravel Version

11.21.0

### Which operating systems does with happen with?

Windows, Linux

### Notes

Using Filament v3.2.108

**Comment by schmeits** [comment] 2024-08-29 09:28
Hi there... unfortunately, I can't reproduce? see attached video for my local dev (windows, Laravel 11.21, PHP 8.3.3, Filament 3.2.108)

https://github.com/user-attachments/assets/80efb948-ea1c-47c3-a350-c297348127fa

Are there any console errors?

**Comment by elegasoft** [comment] 2024-08-30 20:56
Sorry, I over simplified the example, I have updated it to provided a code sample which will break and I provided a video. No, there were no console errors. 

https://github.com/user-attachments/assets/74f2cad4-32c9-4fff-95f6-4eb29a75b3e2

**Comment by schmeits** [comment] 2024-09-02 10:46
Hi there... still not able to reproduce in my test environment? Maybe another plugin conflicting somewhere? Which composer packages are you using so I can try to reproduce.

https://github.com/user-attachments/assets/ffcf8e5e-8f33-4aac-b145-b2e12280162b

**Comment by elegasoft** [comment] 2024-09-03 18:14
Here's the `composer.json`, I'd bet on a package conflict with `mohamedsabil83/filament-forms-tinyeditor`, looks like this package is using an older version of TinyMCE.

```json
    "require": {
        "php": "^8.2",
        "ariaieboy/filament-currency": "^1.8",
        "awcodes/filament-quick-create": "^3.4",
        "bezhansalleh/filament-shield": "^3.2",
        "filament/filament": "^3.2",
        "guzzlehttp/guzzle": "^7.9",
        "laravel/framework": "^11.9",
        "laravel/reverb": "^1.0",
        "laravel/tinker": "^2.9",
        "laravel/vonage-notification-channel": "^3.3",
        "livewire/livewire": "^3.5",
        "livewire/volt": "^1.0",
        "mohamedsabil83/filament-forms-tinyeditor": "^2.3",
        "propaganistas/laravel-phone": "^5.3",
        "saade/filament-fullcalendar": "^3.2",
        "schmeits/filament-character-counter": "^1.3",
        "stechstudio/filament-impersonate": "^3.13",
        "symfony/http-client": "^7.1",
        "symfony/mailgun-mailer": "^7.1",
        "ysfkaya/filament-phone-input": "^3.0"
    },
  
    ```

**Comment by schmeits** [comment] 2024-09-04 07:20
This is weird... installed almost all your packages and it still works. The RichEditor is using trix so an old MCE should not be the problem.
You tried:
```PHP
php artisan filament:assets
php artisan filament:optimize-clear
php artisan filament:clear-cached-components
```

**Comment by schmeits** [comment] 2024-09-05 07:00
Any chance of reproducing it in a clean repo / reproduction repo? Otherwise, I'll close this issue for now.

**Closed** 2024-09-06 20:04 UTC
Labels: bug
